# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'tempo'
    static_configs:
    - targets: ['tempo:3200']
  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
#  - job_name: cadvisor
#    static_configs:
#      - targets: ['cadvisor:9080']
