apiVersion: 1

datasources:
  - name: Prometheus Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    uid: prometheus
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "default"
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderName2: "Connection"
      httpHeaderName3: "Upgrade"
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: $${__value.raw}
    secureJsonData:
      httpHeaderValue1: "default"
      httpHeaderValue2: "Upgrade"
      httpHeaderValue3: "websocket"
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
    secureJsonData:
      httpHeaderValue1: "default"
