apiVersion: 1

datasources:
  - name: Prometheus Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    uid: prometheus
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
    secureJsonData:
      httpHeaderValue1: "default"
  - name: Loki
    type: loki
    typeName: Loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderName2: "Connection"
      httpHeaderName3: "Upgrade"
      derivedFields:
        - datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          name: TraceID
          url: $${__value.raw}
    secureJsonData:
      httpHeaderValue1: "default"
      httpHeaderValue2: "Upgrade"
      httpHeaderValue3: "websocket"
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: 0
        spanEndTimeShift: 0
        tags: []
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | trace_id ="$${__trace.traceId}" and span_id ="$${__span.spanId}"'
    secureJsonData:
      httpHeaderValue1: "default"
