apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://nginx:8080/prometheus
    isDefault: true
    version: 1
    editable: false
    basicAuth: true
    basicAuthUser: default
    uid: prometheus
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
    secureJsonData:
      basicAuthPassword: default
  - name: Loki
    type: loki
    typeName: Loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://nginx:8080
    isDefault: false
    editable: false
    basicAuth: true
    basicAuthUser: default
    jsonData:
      httpHeaderName1: "Connection"
      httpHeaderName2: "Upgrade"
      derivedFields:
        - datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          name: TraceID
          url: $${__value.raw}
    secureJsonData:
      basicAuthPassword: default
      httpHeaderValue1: "Upgrade"
      httpHeaderValue2: "websocket"
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://nginx:8080/tempo
    isDefault: false
    version: 1
    editable: false
    basicAuth: true
    basicAuthUser: default
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: 0
        spanEndTimeShift: 0
        tags: []
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | trace_id ="$${__trace.traceId}" and span_id ="$${__span.spanId}"'
    secureJsonData:
      basicAuthPassword: default
