receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

processors:
  batch:
    metadata_keys:
    - X-Username

exporters:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    auth:
      authenticator: headers_setter
  otlphttp/tempo:
    endpoint: http://tempo:4318
    auth:
      authenticator: headers_setter
  otlphttp/mimir:
    endpoint: http://mimir:9009/otlp
    auth:
      authenticator: headers_setter

service:
  extensions: [headers_setter]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/mimir]
  telemetry:
    logs:
      level: "error"

extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-Scope-OrgID
        from_context: X-Username
