server:
  http_listen_port: 9080
  grpc_listen_port: 9095
  log_level: "error"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: default

scrape_configs:
  - job_name: lokipush
    loki_push_api:
      server:
        http_listen_port: 3500
        grpc_listen_port: 3600
      labels:
        pushserver: lokipush
      use_incoming_timestamp: true
    pipeline_stages:
      - match:
          selector: '{container="dropexample"}'
          action: drop
  - job_name: gelf
    gelf:
      listen_address: 0.0.0.0:12201
      use_incoming_timestamp: true
      labels:
        job: gelf
    relabel_configs:
      - action: replace
        source_labels:
          - __gelf_message_level
        target_label: level
      - action: replace
        source_labels:
          - __gelf_message_host
        target_label: host
      - action: replace
        source_labels:
          - __gelf_message_facility
        target_label: facility
  - job_name: containerlogs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 2s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
    pipeline_stages:
      - static_labels:
          host: "HOSTNAME"
          job: docker.sock
  #- job_name: system
  #  static_configs:
  #    - targets:
  #        - localhost
  #      labels:
  #        job: varlogs
  #        __path__: /var/log/*log
