global:
  scrape_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "mimir"
    static_configs:
      - targets: ["mimir:9090"]
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

remote_write:
  - url: http://mimir:9009/api/v1/push
    headers:
      X-Scope-OrgID: default
