global:
  scrape_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

remote_write:
  - url: http://nginx:8080/prometheus/api/v1/push
    basic_auth:
      username: "default"
      password: "default"

remote_read:
  - url: "http://nginx:8080/prometheus/api/v1/read"
    basic_auth:
      username: "default"
      password: "default"
